GET http://127.0.0.1:5000/


### create user

POST http://127.0.0.1:5000/api/users/register
Content-Type: application/json

{
  "username": "cooluser12345",
  "email": "coollll.user@example.com",
  "password": "mysecretpassword"
}